### ISSUE TITLE
Script `generate_sample_sheet.py` is not compatible with some filenames.

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#88]
_**(Bug reported by @jeroencremer via Slack)**_

Given samples with names:

```
DIA03-12_S138_R1_001_subsampled_10pct.fastq
DIA03-12_S138_R2_001_subsampled_10pct.fastq
DIA03-26_S116_R1_001_subsampled_10pct.fastq
DIA03-26_S116_R2_001_subsampled_10pct.fastq
DIA03-27_S128_R1_001_subsampled_10pct.fastq
DIA03-27_S128_R2_001_subsampled_10pct.fastq
DIA03-52_S143_R1_001_subsampled_10pct.fastq
DIA03-52_S143_R2_001_subsampled_10pct.fastq
DIA04-15_S170_R1_001_subsampled_10pct.fastq
DIA04-15_S170_R2_001_subsampled_10pct.fastq
DIA04-23_S171_R1_001_subsampled_10pct.fastq
DIA04-23_S171_R2_001_subsampled_10pct.fastq
DIA04-59_S132_R1_001_subsampled_10pct.fastq
DIA04-59_S132_R2_001_subsampled_10pct.fastq
DIA04-61_S156_R1_001_subsampled_10pct.fastq
DIA04-61_S156_R2_001_subsampled_10pct.fastq
DIA06-06_S157_R1_001_subsampled_10pct.fastq
DIA06-06_S157_R2_001_subsampled_10pct.fastq
DIA06-28_S136_R1_001_subsampled_10pct.fastq
DIA06-28_S136_R2_001_subsampled_10pct.fastq
DIAG01-10_S110_R1_001_subsampled_10pct.fastq
DIAG01-10_S110_R2_001_subsampled_10pct.fastq
hDIA02-44_S138_R1_001_subsampled_10pct.fastq
hDIA02-44_S138_R2_001_subsampled_10pct.fastq
hDIA02-45_S150_R1_001_subsampled_10pct.fastq
hDIA02-45_S150_R2_001_subsampled_10pct.fastq
```

And the regex contained in `bin/generate_sample_sheet.py`:

`fq_pattern = re.compile("(.*)_R?(1|2).*\.f(ast)?q(\.gz)?")`

Results in this error:
```
Starting snakemake
Building DAG of jobs...
KeyError in line 138 of /data/BioGrid/cremerj/Nextseq_Dtest/Snakefile:
'R2'
 File "/data/BioGrid/cremerj/Nextseq_Dtest/Snakefile", line 138, in <genexpr>
```

And generates this `sample_sheet.yaml`:
```
DIA03-12_S138_R1_001_subsampled:
  R1: raw_data_10/DIA03-12_S138_R1_001_subsampled_10pct.fastq
DIA03-12_S138_R2_001_subsampled:
  R1: raw_data_10/DIA03-12_S138_R2_001_subsampled_10pct.fastq
DIA03-26_S116_R1_001_subsampled:
  R1: raw_data_10/DIA03-26_S116_R1_001_subsampled_10pct.fastq
DIA03-26_S116_R2_001_subsampled:
  R1: raw_data_10/DIA03-26_S116_R2_001_subsampled_10pct.fastq
DIA03-27_S128_R1_001_subsampled:
  R1: raw_data_10/DIA03-27_S128_R1_001_subsampled_10pct.fastq
DIA03-27_S128_R2_001_subsampled:
  R1: raw_data_10/DIA03-27_S128_R2_001_subsampled_10pct.fastq
DIA03-52_S143_R1_001_subsampled:
  R1: raw_data_10/DIA03-52_S143_R1_001_subsampled_10pct.fastq
DIA03-52_S143_R2_001_subsampled:
  R1: raw_data_10/DIA03-52_S143_R2_001_subsampled_10pct.fastq
DIA04-15_S170_R1_001_subsampled:
  R1: raw_data_10/DIA04-15_S170_R1_001_subsampled_10pct.fastq
DIA04-15_S170_R2_001_subsampled:
  R1: raw_data_10/DIA04-15_S170_R2_001_subsampled_10pct.fastq
DIA04-23_S171_R1_001_subsampled:
  R1: raw_data_10/DIA04-23_S171_R1_001_subsampled_10pct.fastq
DIA04-23_S171_R2_001_subsampled:
  R1: raw_data_10/DIA04-23_S171_R2_001_subsampled_10pct.fastq
DIA04-59_S132_R1_001_subsampled:
  R1: raw_data_10/DIA04-59_S132_R1_001_subsampled_10pct.fastq
DIA04-59_S132_R2_001_subsampled:
  R1: raw_data_10/DIA04-59_S132_R2_001_subsampled_10pct.fastq
DIA04-61_S156_R1_001_subsampled:
  R1: raw_data_10/DIA04-61_S156_R1_001_subsampled_10pct.fastq
DIA04-61_S156_R2_001_subsampled:
  R1: raw_data_10/DIA04-61_S156_R2_001_subsampled_10pct.fastq
DIA06-06_S157_R1_001_subsampled:
  R1: raw_data_10/DIA06-06_S157_R1_001_subsampled_10pct.fastq
DIA06-06_S157_R2_001_subsampled:
  R1: raw_data_10/DIA06-06_S157_R2_001_subsampled_10pct.fastq
DIA06-28_S136_R1_001_subsampled:
  R1: raw_data_10/DIA06-28_S136_R1_001_subsampled_10pct.fastq
DIA06-28_S136_R2_001_subsampled:
  R1: raw_data_10/DIA06-28_S136_R2_001_subsampled_10pct.fastq
DIAG01-10_S110_R1_001_subsampled:
  R1: raw_data_10/DIAG01-10_S110_R1_001_subsampled_10pct.fastq
DIAG01-10_S110_R2_001_subsampled:
  R1: raw_data_10/DIAG01-10_S110_R2_001_subsampled_10pct.fastq
hDIA02-44_S138_R1_001_subsampled:
  R1: raw_data_10/hDIA02-44_S138_R1_001_subsampled_10pct.fastq
hDIA02-44_S138_R2_001_subsampled:
  R1: raw_data_10/hDIA02-44_S138_R2_001_subsampled_10pct.fastq
hDIA02-45_S150_R1_001_subsampled:
  R1: raw_data_10/hDIA02-45_S150_R1_001_subsampled_10pct.fastq
hDIA02-45_S150_R2_001_subsampled:
  R1: raw_data_10/hDIA02-45_S150_R2_001_subsampled_10pct.fastq
```

Reason:
The regex does a greedy expand into `hDIA02-45_S150_R2_001_subsampled_1` instead of the intended `hDIA02-45_S150`. Then the basenames are no longer identical and the R1 and R2 paths get assigned to different samples and are no longer considered paired which causes Jovian to error.

Solution:

`fq_pattern = re.compile("(.*)_R?(1|2)(?:_.*\.|\..*\.|\.)f(ast)?q(\.gz)?")`

This will match the intended basename while also making sure that filenames ending with `_R?(1|2).f(ast)?q(\.gz)?` work properly. This is done by using a non-capturing capture group (syntax: `(?:foo|bar)`) for the three allowed character blocks; either `_.*\.` or `\..*\.` or `\.`. The reason for the non-capture capture group is to avoid downstream problems.

I'll push this patch to the `dev` branch. In the meanwhile, above you'll find the fix.
